pragma Singleton
import QtQuick

QtObject {
    readonly property var palettes: ({
        "catppuccin-mocha": {
            base:     "#1e1e2e",
            mantle:   "#181825",
            crust:    "#11111b",
            surface0: "#313244",
            surface1: "#45475a",
            surface2: "#585b70",
            overlay0: "#6c7086",
            text:     "#cdd6f4",
            subtext0: "#a6adc8",
            subtext1: "#bac2de",
            lavender: "#b4befe",
            mauve:    "#cba6f7",
            pink:     "#f5c2e7",
            red:      "#f38ba8",
            peach:    "#fab387",
            yellow:   "#f9e2af",
            green:    "#a6e3a1",
            teal:     "#94e2d5",
            sky:      "#89dceb",
            blue:     "#89b4fa",
            rosewater:"#f5e0dc"
        },
        "catppuccin-latte": {
            base:     "#eff1f5",
            mantle:   "#e6e9ef",
            crust:    "#dce0e8",
            surface0: "#ccd0da",
            surface1: "#bcc0cc",
            surface2: "#acb0be",
            overlay0: "#9ca0b0",
            text:     "#4c4f69",
            subtext0: "#6c6f85",
            subtext1: "#5c5f77",
            lavender: "#7287fd",
            mauve:    "#8839ef",
            pink:     "#ea76cb",
            red:      "#d20f39",
            peach:    "#fe640b",
            yellow:   "#df8e1d",
            green:    "#40a02b",
            teal:     "#179299",
            sky:      "#04a5e5",
            blue:     "#1e66f5",
            rosewater:"#dc8a78"
        },
        "nord": {
            base:     "#2e3440",
            mantle:   "#292e39",
            crust:    "#242933",
            surface0: "#3b4252",
            surface1: "#434c5e",
            surface2: "#4c566a",
            overlay0: "#616e88",
            text:     "#eceff4",
            subtext0: "#d8dee9",
            subtext1: "#e5e9f0",
            lavender: "#b48ead",
            mauve:    "#b48ead",
            pink:     "#b48ead",
            red:      "#bf616a",
            peach:    "#d08770",
            yellow:   "#ebcb8b",
            green:    "#a3be8c",
            teal:     "#8fbcbb",
            sky:      "#88c0d0",
            blue:     "#81a1c1",
            rosewater:"#d8dee9"
        },
        "dracula": {
            base:     "#282a36",
            mantle:   "#1e1f29",
            crust:    "#191a21",
            surface0: "#44475a",
            surface1: "#4d4f68",
            surface2: "#565976",
            overlay0: "#6272a4",
            text:     "#f8f8f2",
            subtext0: "#bfbfbf",
            subtext1: "#e0e0e0",
            lavender: "#bd93f9",
            mauve:    "#bd93f9",
            pink:     "#ff79c6",
            red:      "#ff5555",
            peach:    "#ffb86c",
            yellow:   "#f1fa8c",
            green:    "#50fa7b",
            teal:     "#8be9fd",
            sky:      "#8be9fd",
            blue:     "#6272a4",
            rosewater:"#f8f8f2"
        },
        "gruvbox": {
            base:     "#282828",
            mantle:   "#1d2021",
            crust:    "#1b1b1b",
            surface0: "#3c3836",
            surface1: "#504945",
            surface2: "#665c54",
            overlay0: "#7c6f64",
            text:     "#ebdbb2",
            subtext0: "#bdae93",
            subtext1: "#d5c4a1",
            lavender: "#d3869b",
            mauve:    "#d3869b",
            pink:     "#d3869b",
            red:      "#fb4934",
            peach:    "#fe8019",
            yellow:   "#fabd2f",
            green:    "#b8bb26",
            teal:     "#8ec07c",
            sky:      "#83a598",
            blue:     "#83a598",
            rosewater:"#ebdbb2"
        }
    })

    function getPalette(name) {
        return palettes[name] || palettes["catppuccin-mocha"];
    }
}
